Styles polishing
actum/aria-hooks pull request #17
Opened 2021-11-18 10:18 UTC by MatejVykoukal

2021-11-19 11:11 UTC, zmrhaljiri requested changes

2021-11-19 11:11 UTC, zmrhaljiri commented on src/hooks/tooltip/tooltip.stories.mdx
> +Most commonly displays description of a button's function or hint on keyboard shortcut to activate functionality.
```suggestion
A component that displays informative text on hover, focus, or tap.

It can be used to display a description of a button's function or hint on keyboard shortcut to activate functionality.
```

2021-11-19 11:11 UTC, zmrhaljiri commented on src/hooks/drawer/drawer.stories.mdx
> +Component that is hidden by default and opened upon an action, usually a button click.
```suggestion
A component that is hidden by default and is opened upon an action, usually a button interaction.
```

2021-11-19 11:11 UTC, zmrhaljiri commented on src/hooks/listbox/listbox.stories.mdx
> +Component that allows the user to choose one value from a list. When a listbox is inactive, it displays a single value. When activated, it displays a list of values, from which the user may select on
```suggestion
A component that allows the user to choose one value from a list. When a listbox is inactive, it displays a single value. When activated, it displays a list of values, from which the user may select one. When the user selects a new value, listbox becomes inactive again, displaying the selected value.
```

2021-11-19 11:11 UTC, zmrhaljiri commented on src/hooks/modal/modal.stories.mdx
> +Most commonly it should draw attention to vital pieces of information or block the application flow until information required to continue is entered.
```suggestion
A component that creates a mode that disables the main window but keeps it visible, with the modal window as a child window in front of it. Users must interact with the modal window before they can return to the parent window.

Most commonly it should draw attention to vital pieces of information or block the application flow until the information required to continue is entered.
```

2021-11-19 11:11 UTC, zmrhaljiri commented on src/hooks/tooltip/tooltip.component.tsx
>        <StyledTooltip {...toolTipProps}>I am the tool tip </StyledTooltip>
```suggestion
      <StyledTooltip {...toolTipProps}>I am the tooltip </StyledTooltip>
```

2021-11-19 11:11 UTC, zmrhaljiri commented on src/hooks/navigation/menubar.styles.ts
> +    /* &:focus, */
Maybe we can delete this if not used :)

2021-11-19 11:11 UTC, zmrhaljiri commented on src/styles/variables.ts
> +  '3-xl': '2.4rem',
Why not xxxl? Don't like it? :D

2021-11-19 11:11 UTC, zmrhaljiri commented on src/styles/variables.ts
> +// export const spacers = Object.fromEntries(keyPaireSpacers);
We can remove it if it's not stored here for the future reference)

2021-11-19 11:50 UTC, MatejVykoukal commented on src/styles/variables.ts
> +  '3-xl': '2.4rem',
If we will later add more font sizes, it could become confusing.

2021-11-19 13:11 UTC, zmrhaljiri commented on src/styles/variables.ts
> +  '3-xl': '2.4rem',
Agree, but maybe we should stick to a fewer sizes rather than more))

2021-12-03 00:41 UTC, zmrhaljiri requested changes

2021-12-03 00:41 UTC, zmrhaljiri commented on .storybook/manager-head.html
> +  svg#Capa_1 {
When the dark mode is applied, another icon is shown (without an ID), so I suggest using something like `.os-content svg` selector.

2021-12-03 10:13 UTC, MatejVykoukal commented on .storybook/manager-head.html
> +  svg#Capa_1 {
.os-content class is in multiple places(eg. sidebar), so when using mentioned selector many icons are influenced. I'll try to come up with a more specific selector. 
![image](https://user-images.githubusercontent.com/61636415/144585579-6cc480a0-36d2-4a9c-bdbe-374e956c58b2.png)

2021-12-03 11:07 UTC, zmrhaljiri commented on .storybook/manager-head.html
> +  svg#Capa_1 {
Yep makes sense, thanks))

2021-12-03 14:07 UTC, zmrhaljiri approved these changes

2021-12-03 14:13 UTC, merged